config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'

  get 'comments/update'

  get 'comments/delete'

  get 'comments/view'

  get 'user_task/index'

  get 'user_task/create'

  get 'user_project/index'

  get 'user_project/create'

  resources :users
  resources :tasks do
    get :assign_users_form, on: :member
    post :assign_users, on: :member
  end
  resources :projects do
    get :assign_users_form, on: :member
    post :assign_users, on: :member
  end

  resources :user_projects
  resources :user_tasks
  resources :comments

  root 'projects#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project
  has_and_belongs_to_many :users, dependent: :destroy
  has_many :comments
	validates :name, presence: true

  STATUS = {
    pending: 'Pending',
    process: 'Process',
    done: 'Done'
  }.freeze

  LABEL = {
    feature: 'Feature',
    Enhancement: 'Enhancement',
    bug: 'Bug',
    rework: 'Rework', 
    ui_work: 'UI-Work' 

  }.freeze


  def done?
    status == STATUS[:done]
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :assign_users_form, :assign_users]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @comment = Comment.new
    @comments = Comment.where(task_id: @task.id)
  end

  # GET /tasks/new
  def new
    @task = Task.new
    #params[:project_id].inspect
  end

  # GET /tasks/1/edit
  def edit
  end

  def assign_users_form
    @users = User.all
  end


  def assign_users
     @task.user_ids = params[:task][:user_ids] rescue []
    if @task.save
      redirect_to @task, notice: "Users added successfully."
    else
      redirect_to assign_users_form_task_path(@task), alert: "Error: #{task.errors.full_messages.join(",")}"
    end   
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    #if @task.done
      #redirect_to @task, notice: 'Task already done.'
    #else
      respond_to do |format|
        if @task.update(task_params)
          format.html { redirect_to tasks_path, notice: 'Task was successfully updated.' }
          format.json { render :show, status: :ok, location: @task }
        else
          format.html { render :edit }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    #end
  end

  # DELETE /tasks/1
  # DELETE /tSasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
      #s@comment = Comment.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:project_id, :name, :status, :due_date, :label, :done, :user_ids => [])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="container">
  <%= simple_form_for @task do |f| %>
    <div class="col">
      <div class="col-sm">
        <%= f.association :project, collection: Project.all, label_method: :name, value_method: :id,
          prompt: "Select Project" %>
      </div>
      <div class="col-sm">
         <%= f.input :name %>
       </div>
       <div class="col-sm">
         <%= f.input :status, collection: Task::STATUS.values %>
        
      </div>
      <div class="col-sm">
         <%= f.text_field :due_date, :id => "datepicker", :value => Date.today %>
        
      </div>
      <div class="col-sm">
         <%= f.input :label, collection: Task::LABEL.values %>
        
      </div>
      <div class="col-sm">
         <%#= f.input :done %>
      </div>
      <div class="col-sm">     
       <%= f.button :submit, class: "btn-success" %>
      </div>

    </div>
  <% end %>
</div>

<script type="text/javascript">
  $('#datepicker').datepicker({format: 'yyyy-mm-dd'});
</script>

app/views/tasks/assign_users_form.html.erb
<center><h3> Assign users to Task <%= @task.name %></h3></center>
<br></br>
<div class="container">
  <%= simple_form_for @task, url: "assign_users", method: "post", 
    html: { class: "form-horizontal" } do |f| %>
    <%= f.error_notification %>
    <% @task.project.users.all.each do |user| %>
      <%= check_box_tag "task[user_ids][]", user.id, @task.user_ids.include?(user.id) %>
      <%= user.name_with_email %>
      <br>
    <% end %>
    
    <div class="row">  
      <div class="col-md-4 offset-md-4"></div>   
        <%= f.button :submit, "Assign User", class: "btn btn-success" %>
      </div> 
    </div>
  </div>
<% end %>

<%= link_to 'Back', tasks_path, class: "btn btn-secondary" %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task, class: "btn btn-info" %> |
<%= link_to 'Back', tasks_path, class: "btn btn-secondary" %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <div class="container">           
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Project</th>
          <th>Name</th>
          <th>Status</th>
          <th>Due date</th>
          <th>Label</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td><%= task.project.name %></td>
            <td><%= task.name %></td>
            <td class="<%= task.status %>"><%= task.status %></td>
            <td><%= task.due_date %></td>
            <td><%= task.label %></td>
            <td>
              <div class="btn-stack">
                <%= link_to 'Assign Users', assign_users_form_task_path(task.id), 
                  class: "btn btn-primary" if task.project.users.count > 0 %>
                <%= link_to 'Show', task, class: "btn btn-success" unless task.done? %>
                <%= link_to 'Edit', edit_task_path(task), class: "btn btn-info" unless task.done? %>
                <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</table>

<br>

<%= link_to 'Add Task', new_task_path, class: "btn btn-primary" %>
<%= link_to 'Back', projects_path, class: "btn btn-info" %>

<style type="text/css">
  .Pending {
    background: #f2d227;
  }
  .Done {
    background: #4eef1c;
  }
  .Process {
    background: #44f3c1;
  }
</style>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path, class: "btn btn-secondary" %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th colspan="2"><center>Task Details</center></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><strong>Project</strong></td>
        <td><%= @task.project.name %> </td>
      </tr>

      <tr>
        <td><strong>Name:</strong></td>
        <td><%= @task.name %></td>
      </tr>

      <tr>
        <td><strong>Status:</strong></td>
        <td><%= @task.status %></td>
      </tr>
      <tr>
        <td><strong>Due date:</strong></td>
        <td><%= @task.due_date %></td>
      </tr>
      <tr>
        <td><strong>Label:</strong></td>
        <td><%= @task.label %></td>
      </tr>

      <tr>
        <td><strong>Assigned:</strong></td>
        <td>
          <ul>
            <% @task.users.each do |user| %>
              <%= link_to user do %>
                <li class="list-group">
                  <%= user.name_with_email %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<%= link_to 'Edit', edit_task_path(@task), class: "btn btn-info" %> |
<%= link_to 'Back', tasks_path, class: "btn btn-secondary" %>