config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'

  get 'comments/update'

  get 'comments/delete'

  get 'comments/view'

  get 'user_task/index'

  get 'user_task/create'

  get 'user_project/index'

  get 'user_project/create'

  resources :users
  resources :tasks do
    get :assign_users_form, on: :member
    post :assign_users, on: :member
  end
  resources :projects do
    get :assign_users_form, on: :member
    post :assign_users, on: :member
  end

  resources :user_projects
  resources :user_tasks
  resources :comments

  root 'projects#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :projects
	has_and_belongs_to_many :tasks
	validates :name, presence: :true
	validates :phone,:presence => true, :numericality => true, :length => { :minimum => 10, :maximum => 15 }
	validates :email, presence: true, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/

  USER_ROLES = ["Admin", "Employee"].freeze

  DEPARTMENTS = ["Project"]



  def name_with_email
    "#{self.name} - #{self.email}"
  end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :phone, :department, :user_type)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="container">
      <div class="col">
        <div class="col-sm">

          <div class="form-inputs">
            <%= f.input :name %>
            <%= f.input :email %>
            <%= f.input :phone %>
            <%= f.input :department %>
            <%= f.input :user_type %>
          </div>
        </div>
      </div>
    </div>

    <div class="form-actions">
        <%= f.button :submit,  class: "btn-primary"%>
    </div>
  

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user, class: "btn btn-success" %> |
<%= link_to 'Back', users_path, class: "btn btn-secondary" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
    <div class="container">           
        <table class="table table-striped">
          <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Department</th>
                <th>User type</th>
                <th colspan="3"></th>
              </tr>
          </thead>
        
    </div>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.department %></td>
        <td><%= user.user_type %></td>
        <td><%= link_to 'Show', user, class: "btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New User', new_user_path, class: "btn btn-primary" %>
<%= link_to 'Back', tasks_path, class: "btn btn-info" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, class: "btn btn-secondary" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th colspan="2"><center>User Details</center></th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><strong>Name:</strong></td>
        <td><%= @user.name %></td>
      </tr>

      <tr>
        <td><strong>Email:</strong></td>
        <td><%= @user.email %></td>
      </tr>

      <tr>
        <td><strong>Phone:</strong></td>
        <td><%= @user.phone %></td>
      </tr>

      <tr>
        <td><strong>Department:</strong></td>
        <td><%= @user.department %></td>
      </tr>

      <tr>
        <td><strong>User type:</strong></td>
        <td><%= @user.user_type %></td>
      </tr>
    </tbody>
  </table>
</div>

<%= link_to 'Edit', edit_user_path(@user), class: "btn btn-info" %> |
<%= link_to 'Back', users_path, class: "btn btn-primary" %>