config/routes.rb
Rails.application.routes.draw do

  get 'comments/create'

  get 'comments/update'

  get 'comments/delete'

  get 'comments/view'

  get 'user_task/index'

  get 'user_task/create'

  get 'user_project/index'

  get 'user_project/create'

  resources :users
  resources :tasks do
    get :assign_users_form, on: :member
    post :assign_users, on: :member
  end
  resources :projects do
    get :assign_users_form, on: :member
    post :assign_users, on: :member
  end

  resources :user_projects
  resources :user_tasks
  resources :comments

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks, dependent: :destroy
  has_and_belongs_to_many :users, dependent: :destroy
  validates :name, presence: :true
  validates :client_details, presence: :true 
  validates :description, :presence => true, :length => { :maximum => 1024 }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :assign_users_form, :assign_users]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # GET /projects/:id/assign_users_form
  def assign_users_form
    @users = User.all
  end

   # GET /projects/:id/assign_users
  def assign_users
    @project.user_ids = params[:project][:user_ids] rescue []
    if @project.save
      redirect_to @project, notice: "Users added successfully."
    else
      redirect_to assign_users_form_project_path(@project), alert: "Error: #{project.errors.full_messages.join(",")}"
    end    
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

   # POST /projects
  # POST /projects.json
  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :client_details, :user_ids => [])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="container">
  <%= simple_form_for @project do |f| %>
    <div class="col">
      <div class="col-sm">
        <%= f.input :name %>
      </div>

      <div class="col-sm-4">
        <%= f.input :description %>
      </div>

      <div class="col-sm-4">
        <%= f.input :client_details %>
      </div>

      <div class="col-sm-4"> 
        <%= f.button :submit, class: "btn-success" %>
      </div> 
  <% end %>
</div>

app/views/projects/assign_users_form.html.erb
<center><h3>Assign users to Project <%= @project.name %></h3></center>
<br><br>
<div class="container">
  <%= simple_form_for @project, url: "assign_users", method: "post", 
    html: { class: "form-horizontal" } do |f| %>
    <%= f.error_notification %>
    
    <% User.all.each do |user| %>
      <%= check_box_tag "project[user_ids][]", user.id, @project.user_ids.include?(user.id) %>
      <%= user.name_with_email %>
      <br>
    <% end %>
 
    <div class="row">  
      <div class="col-md-4 offset-md-4"></div>
        <%= f.submit class: "btn-success" %>
      </div>
  <% end %>
</div>

<%= link_to 'Back', projects_path, class: "btn btn-secondary" %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project, class: "btn btn-info" %> |
<%= link_to 'Back', projects_path, class: "btn btn-secondary" %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
<div class="container"> 
  <div class="row">
    <div class="col-md-4 offset-md-4">         
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Client details</th>
            <th colspan="3"></th>
          </tr>
        </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.client_details %></td>
        <td>
          <div class="btn-stack">
            <%= link_to 'Show', project, class: "btn btn-success" %>
            <%= link_to 'Assign Users', assign_users_form_project_path(project.id), class: "btn btn-primary" %>
            <%= link_to 'Edit', edit_project_path(project),  class: "btn btn-info"  %>
            <%= link_to 'Tasks', tasks_path(project_id: project.id), class: "btn btn-secondary" %>
            <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, 
              class: "btn btn-danger" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</div>
</div>
</table>

<br>

<%= link_to 'Add Project', new_project_path, class: "btn btn-primary" %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path, class: "btn btn-secondary" %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container" >
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th colspan="2"><center>Project Details</center></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><strong>Name:</strong></td>
        <td><%=@project.name %></td>
      </tr>

      <tr>
        <td><strong>Description:</strong></td>
        <td><%=@project.description %></td>
      </tr>

      <tr>
        <td><strong>Client details:</strong></td>
        <td><%=@project.client_details%></td>
      </tr>

      <tr>
        <td><strong>Assignee:</strong></td>
        <td>
          <ul>
            <% @project.users.each do |user| %>
              <%= link_to user do %>
                <li class="list-group">
                  <%= user.name_with_email %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </td>
      </tr>

      <tr>
        <td><strong>Tasks List:</strong></td>
        <td>
          <ul>
            <% @project.tasks.each do |task| %>
              <%= link_to task do %>
                <li class="list-group">
                  <%= "#{task.name} - Status: #{task.status}" %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<%= link_to 'Edit', edit_project_path(@project), class: "btn btn-info" %> |
<%= link_to 'Back', projects_path, class: "btn btn-secondary" %>